server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ETICARET_URL}
    username: ${ETICARET_USERNAME}
    password: ${ETICARET_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update